# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pyinstaller-window-compile

on:
  push:
    branches: [ dist ]
  pull_request:
    branches: [ dist ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    - name: build exe file
      run: |
        pyinstaller --onefile dist\window-build.spec
    - name: commit and push
      shell: cmd
      run: |
        git config --global user.name 'binchoo'
        git config --global user.email 'jbinchoo@gmail.com'
        git add dist
        git commit -m "Build windows binary."
        git pull
        git push
